### ISSUE TITLE
Helper not displaying proper UI

### ISSUE THREAD

**Issue by achecchia** [sillyfrog/Tasmota-Tuya-Helper#11]
I have a device that i configured using the helper a few months back and it was awesome. Since then, i've updated the firmware and no longer get a proper UI. i'm concerned that when i go to configure a newly flashed device, i wont be able to use the helper to configure it. My device is on Tasmota 12.2.0. the screenshot will show you what i see.
<img width="1279" alt="Screen Shot 2023-04-29 at 8 14 38 AM" src="https://user-images.githubusercontent.com/53822466/235302045-bd4fdb24-0730-4c40-be9a-cfcb0e4e7d10.png">

**Comment by sillyfrog** [comment]
I've just tested with v12.5 and it appears to be working. Are you able to please try updating to the latest Tasmota and see if that works? Also check you have the latest version of this Bookmarklet.
The commands to configure are the same in the latest Tasmota, so if the configuration is lost (it shouldn't be), you can use the same `backlog` command to configure it again worst case.
If it doesn't work, we'll need to look at the developer tools in your browser and see what errors there are and we can then look to address.

**Comment by alfakenzo** [comment]
Hi sillyfrog, I have the same problem I updated to tasmota 13 used newest tuya-helper and get the Sam result like achecchia. I use Firefox and Chrome both the same. Maybe you have the time to check this great helper!
Greats

**Comment by hildebrau** [comment]
I'm having a similar UI issue.  I just installed the bookmarklet into Chrome and Firefox.. both are showing similar:

<img width="1583" alt="image" src="https://github.com/sillyfrog/Tasmota-Tuya-Helper/assets/2652477/9f6375c9-2d47-4781-99ac-581089d1558e">

Did I miss a step, or what?
