### ISSUE TITLE
Add support for  browser darke mode

### ISSUE THREAD

**Issue by g6094199** [sillyfrog/Tasmota-Tuya-Helper#12]
hi

it would be nice to have it working on dark mode browser setting.

see FF in dark mode:

![grafik](https://github.com/sillyfrog/Tasmota-Tuya-Helper/assets/37833326/380cae71-bf3b-4a86-be58-bdaf4fdba015)

**Comment by sillyfrog** [comment]
Do you have any other extensions installed? I'm using Firefox and did dark mode, and the text was still white. I also tried in a Private Browser session (ie: most extensions disabled), and still the same.

I'm on Mac OS.

<img width="342" alt="image" src="https://github.com/sillyfrog/Tasmota-Tuya-Helper/assets/816454/d85c44d7-61b0-41e7-9d7d-672fd322fc11">

**Comment by AegisVP** [comment]
I'm on Chrome on Mac and also see black labels

**Comment by sillyfrog** [comment]
Fixed in #13
