### ISSUE TITLE
Table does not get generated

### ISSUE THREAD

**Issue by CaptainDario** [sillyfrog/Tasmota-Tuya-Helper#2]
Tasmota version: 8.4.0
Browser: Firefox

Hello,
I am currently trying to configure Tasmota with [this device](https://www.aliexpress.com/item/4000194764849.html?spm=a2g0s.9042311.0.0.27424c4dXs2w7Q).
Flashing Tasmota with the Tuya Convert tool worked perfectly as always.

But now it seems like the buttons are not controlled via the ESP.
Therefore I am for the first time trying to use TuyaMCU.

I am following [this guide](https://tasmota.github.io/docs/TuyaMCU/) where it is recommended to use your bookmark. However, for me only the header of the table is being generated.

After a few lines it is only writing:
```
WIF: Checking connection...
```
Like this:
![booklet](https://user-images.githubusercontent.com/51273483/90980053-576f8d80-e559-11ea-9aac-0337eb53cae0.jpg)

Your help would be highly appreciated

**Comment by sillyfrog** [comment]
FYI: I have finally just updated the README to make it clear that's what you need to go. Cheers!
