### ISSUE TITLE
New dp type

### ISSUE THREAD

**Issue by ayasystems** [sillyfrog/Tasmota-Tuya-Helper#4]
Could you add new DP types?? 

I think also there are new FnId that are not included in your script. 

Regards!

**Comment by sillyfrog** [comment]
I have added in the new `fnId`s, but not added any of the `dpId`s as I don't have any hardware to test. It should be fairly easy if I have some reference data. If you have a device that is using these, if you can start the bookmarklet and after it's been running for a few seconds, copy the console output to a file, and attach to this issue, I can give it a go.

**Comment by ayasystems** [comment]
Ofcourse...

Is it enought??

13:29:16 {"TuyaReceived":{"Data":"55AA0302000004","Cmnd":2}}
13:29:16 TYA: RX MCU configuration Mode=0
13:29:16 TYA: Read MCU state
13:29:16 TYA: Send "55aa0008000007"
13:29:16 {"TuyaReceived":{"Data":"55AA03070005140100010125","Cmnd":7,"CmndData":"1401000101","DpType1Id20":1,"20":{"DpId":20,"DpIdType":1,"DpIdData":"01"}}}
13:29:16 TYA: fnId=11 is set for dpId=20
13:29:16 TYA: RX Relay-1 --> MCU State: On Current State:On
13:29:16 {"TuyaReceived":{"Data":"55AA03070005150400010129","Cmnd":7,"CmndData":"1504000101","DpType4Id21":1,"21":{"DpId":21,"DpIdType":4,"DpIdData":"01"}}}
13:29:16 TYA: fnId=21 is set for dpId=21
13:29:16 {"TuyaReceived":{"Data":"55AA0307000816020004000003E818","Cmnd":7,"CmndData":"16020004000003E8","DpType2Id22":1000,"22":{"DpId":22,"DpIdType":2,"DpIdData":"000003E8"}}}
13:29:16 TYA: fnId=0 is set for dpId=22
13:29:16 TYA: RX value 1000 from dpId 22 
13:29:16 {"TuyaReceived":{"Data":"55AA0307000817020004000001F423","Cmnd":7,"CmndData":"17020004000001F4","DpType2Id23":500,"23":{"DpId":23,"DpIdType":2,"DpIdData":"000001F4"}}}
13:29:16 TYA: fnId=0 is set for dpId=23
13:29:16 TYA: RX value 500 from dpId 23 
13:29:16 {"TuyaReceived":{"Data":"55AA030700081A0200040000000031","Cmnd":7,"CmndData":"1A02000400000000","DpType2Id26":0,"26":{"DpId":26,"DpIdType":2,"DpIdData":"00000000"}}}
13:29:16 TYA: fnId=0 is set for dpId=26
13:29:16 TYA: RX value 0 from dpId 26 
13:29:16 {"TuyaReceived":{"Data":"55AA030700101803000C30303030303365383033653800","Cmnd":7,"CmndData":"1803000C303030303033653830336538","DpType3Id24":"000003e803e8","24":{"DpId":24,"DpIdType":3,"DpIdData":"303030303033653830336538","Type3Data":"000003e803e8"}}}
13:29:16 TYA: fnId=24 is set for dpId=24
13:29:16 SRC: Switch
13:29:16 CMD: Group 0, Index 1, Command "HSBCOLOR", Data "0,100,100"
13:29:16 MQT: domoticz/in = {"idx":400,"nvalue":1,"svalue":"100","Battery":100,"RSSI":10}
13:29:16 MQT: stat/tasmota_79FDB6/RESULT = {"POWER":"ON","Dimmer":100,"Color":"FF0000","HSBColor":"0,100,100","Channel":[100,0,0]}

Regards!

**Comment by ayasystems** [comment]
This is the device
LED Tuya RGB RGBW
https://es.aliexpress.com/item/4001048211190.html?spm=a2g0s.9042311.0.0.274263c0uOJrrP

I have configure it as follow but i am not able to use withe channel... I tried several combination but only works with 24<->24 as this picture
![tuya_mcu_rgb](https://user-images.githubusercontent.com/7864168/98367793-88c70800-2036-11eb-9820-84a9711777a7.jpg)

**Comment by sillyfrog** [comment]
I have just pushed a new version that should support strings (and Enums). If you can give that a go ASAP, that would be great. Hopefully it will just work.

As per the notes on the Tasmota docs, it can be important to keep the case the same as what you get back (eg: all lower or upper case).

Good luck!

**Comment by ayasystems** [comment]
Hi @sillyfrog 

Now all types are detected Enum and string.

RGB is working fine, I don't know the correct configuration in order to use white channel but I wll try again .... 

![tuya_mcu_rgb](https://user-images.githubusercontent.com/7864168/98436702-c632a080-20dd-11eb-9979-5a97fec72ced.jpg)

Thank you very much for your code and fix
