### ISSUE TITLE
Table not being populated

### ISSUE THREAD

**Issue by titiviking** [sillyfrog/Tasmota-Tuya-Helper#5]
Hi, 

I followed all the isntallation steps, I see the table headers being displayed, but no content.

The table remains empty...

Smart Plug based on ESP8285
Tasmota 9.2.0.1 (successfully flashed through soldering)

```
[16:26:41.812 HTP: Console
16:26:46.850 WIF: Checking connection...
16:26:48.038 CMD: Backlog Weblog 4; TuyaSend8;
16:26:48.040 SRC: WebConsole from 192.168.0.65
16:26:48.043 CMD: Group 0, Index 1, Command "BACKLOG", Data "Weblog 4; TuyaSend8;"
16:26:48.141 SRC: Backlog
16:26:48.144 CMD: Group 0, Index 1, Command "WEBLOG", Data "4"
16:26:48.148 RSL: stat/tasmota_0B6D60/RESULT = {"WebLog":4}
16:26:48.362 SRC: Backlog
16:26:48.365 CMD: Group 0, Index 8, Command "TUYASEND", Data ""
16:26:48.368 TYA: Read MCU state
16:26:48.378 TYA: Send "55aa0001000000"
16:26:48.381 RSL: stat/tasmota_0B6D60/RESULT = {"TuyaSend":"Done"}
16:26:48.471 CMD: TuyaMCU;
16:26:48.474 SRC: WebConsole from 192.168.0.65
16:26:48.477 CMD: Group 0, Index 1, Command "TUYAMCU", Data ";"
16:26:48.481 TYA: TuyaMcu Invalid function id=0
16:26:48.485 RSL: stat/tasmota_0B6D60/RESULT = {"TuyaMCU":[{"fnId":11,"dpId":1}]}
16:26:51.445 TYA: Send "55aa00000000ff"
16:27:02.438 TYA: Send "55aa00000000ff"
16:27:06.843 WIF: Checking connection...
16:27:13.444 TYA: Send "55aa00000000ff"
16:27:24.440 TYA: Send "55aa00000000ff"]
```

**Comment by sillyfrog** [comment]
Best I can tell it's not seeing anything from the Tuya MCU. My first guess would be it's not using the standard Rx and Tx pins. I personally have not seen it on my devices, but know it does happen. If you go to `Configuration > Configure Template', and make sure it's based on: Tuya MCU (54)` - then you can select the "Tuya Rx" and "Tuya Tx" pins. If you have already opened it up, you can probably figure out the pins by following the tracks from the MCU to the ESP - there will probably only be 2 pins, and take a stab and which is Tx and Rx (or if you can see the ID of the MCU, you can probably figure it out from the data sheet).

If it's working, you should see lines such as this in the logs:
```
00:07:00 {"TuyaReceived":{"Data":"55AA0302000004","Cmnd":2}}
00:07:00 TYA: RX MCU configuration Mode=0
00:02:10 TYA: Heartbeat
```

Good luck!

**Comment by vaggelanos** [comment]
Is there any other way to identity which pins are Tx, Rx ? I have found the data sheet of the Tuya MCU (TYLC5) but i had no luck yet . I am to the point of trying every possible combination .. thanks in advance

**Comment by sillyfrog** [comment]
No update for several months, closing.

**Comment by UnbridledGames** [comment]
I know this is way out of date, but for anyone having the same issue, SetOption97 1, changing the TuyaMCU baud rate from 9600 (so97 0) to 115200 (so97 1) fixed the issue. Everything populated and works now. Might be worth adding that into the bookmark - if after X seconds nothing populates, try changing so97?

**Comment by sillyfrog** [comment]
Thanks @UnbridledGames , I have updated and linked to the [Wiki](https://github.com/sillyfrog/Tasmota-Tuya-Helper/wiki/Tips-for-Tuya-Convert), to allow for future updates more easily.
