### ISSUE TITLE
FnId 36 and 37 missing

### ISSUE THREAD

**Issue by chaveiro** [sillyfrog/Tasmota-Tuya-Helper#7]
Tasmota development branch now added this FnId 36 and 37 for TuyaMCU that are missing from this.

Instructions on how to update this script could be cool.

Thanks for the work!

**Comment by sillyfrog** [comment]
This PR made some similar changes: https://github.com/sillyfrog/Tasmota-Tuya-Helper/pull/6

But if you have a link to the documentation (ie: the dev doc's), I'm happy to add it in. I'll update the docs as well to outline upgrading.

Cheers.

**Comment by chaveiro** [comment]
Hi, see here:

https://github.com/arendst/Tasmota/blob/5e3274af8f5c72dceed231e8fc27a98cd9b48d4c/tasmota/tasmota.h#L420

Change was on this PR https://github.com/arendst/Tasmota/commit/5e3274af8f5c72dceed231e8fc27a98cd9b48d4c#

**Comment by sillyfrog** [comment]
Thanks @chaveiro !

Sorry for not getting back to this, got buried in my inbox and it slipped my mind.
